import type { SeedRow } from './exercises_p1'

export const p3: SeedRow[] = [
  // MORE SQUAT / LUNGE (25)
  ['Front Foot Elevated Split Squat', 'ffess', 'squat', 'quads,glutes', 'dumbbell,box', 'weight_reps', ['Drop straight down', 'Keep front foot flat']],
  ['Overhead Squat (Dumbbell)', 'db ohs', 'squat', 'quads,core,shoulders', 'dumbbell', 'weight_reps', ['Press up into the weight', 'Keep armpits forward']],
  ['Cable Squat', 'cable squat', 'squat', 'quads,glutes', 'cable', 'weight_reps', ['Lean back slightly', 'Constant tension']],
  ['Assisted Pistol Squat', 'trx pistol', 'squat', 'quads,glutes', 'suspension trainer', 'reps', ['Use arms only as much as needed', 'Control the eccentric']],
  ['Cossack Squat', 'cossacks', 'squat', 'quads,adductors', 'bodyweight,kettlebell', 'reps', ['Keep the heel of the bent leg down', 'Straight leg toes point up']],
  ['Banded Squat', 'band squat', 'squat', 'quads,glutes', 'band', 'reps', ['Drive out against the band', 'Explode up']],
  ['TRX Squat', 'suspension squat', 'squat', 'quads,glutes', 'suspension trainer', 'reps', ['Keep chest up', 'Use legs, not arms']],
  ['Deficit Curtsy Lunge', 'deficit curtsey', 'lunge', 'glutes', 'dumbbell,box', 'weight_reps', ['Deep stretch', 'Push off the front heel']],
  ['Sliding Side Lunge', 'slider lateral lunge', 'lunge', 'adductors,quads', 'bodyweight', 'reps', ['Slide out under control', 'Pull back using the adductor']],
  ['Walking Lunge (Barbell)', 'bb lunges', 'lunge', 'quads,glutes', 'barbell', 'weight_reps', ['Chest up', 'Don\'t let the bar roll']],
  ['Reverse Lunge (Smith)', 'smith lunge', 'lunge', 'quads,glutes', 'machine', 'weight_reps', ['Step far back', 'Push through front heel']],
  ['Hack Squat (Reverse)', 'reverse hack', 'squat', 'glutes,quads', 'machine', 'weight_reps', ['Face the pad', 'Hinge slightly more than normal']],
  ['Heel Elevated Trap Bar Squat', 'trap bar squat', 'squat', 'quads', 'trap bar', 'weight_reps', ['Stand on wedges', 'Stay extremely upright']],
  ['Bulgarian Split Squat (Barbell)', 'bb bss', 'lunge', 'quads,glutes', 'barbell,bench', 'weight_reps', ['Balance is key', 'Drop the back knee']],
  ['Overhead Reverse Lunge', 'oh rev lunge', 'lunge', 'quads,core', 'barbell,dumbbell', 'weight_reps', ['Lock elbows out', 'Keep ribs pulled down']],

  // MORE HINGE / PULL (25)
  ['Snatch Grip RDL', 'snatch rdl', 'hinge', 'hamstrings,upper back', 'barbell', 'weight_reps', ['Wide grip', 'Keep lats engaged the whole time']],
  ['Deficit RDL', 'deficit rdl', 'hinge', 'hamstrings,glutes', 'barbell', 'weight_reps', ['Stand on a small box', 'Go for maximum stretch']],
  ['Good Morning (Seated)', 'seated gm', 'hinge', 'lower back,glutes', 'barbell,bench', 'weight_reps', ['Wide stance', 'Hinge forward maintaining flat back']],
  ['Cable Pull-Through (Kneeling)', 'kneeling pull through', 'hinge', 'glutes', 'cable', 'weight_reps', ['Kneel on a pad', 'Squeeze glutes at the top']],
  ['Hip Extension', 'hip ext', 'hinge', 'glutes,hamstrings', 'machine', 'weight_reps', ['Round the upper back slightly', 'Focus on glutes']],
  ['Kettlebell Swing (Double)', 'double kb swing', 'hinge', 'glutes,hamstrings', 'kettlebell', 'reps', ['Wide stance', 'Snap the hips hard']],
  ['Dumbbell RDL', 'db rdl', 'hinge', 'hamstrings,glutes', 'dumbbell', 'weight_reps', ['Keep dumbbells sliding down your legs', 'Hinge until hamstrings are tight']],
  ['T-Bar Row (Chest Supported)', 'chest supported t-bar', 'pull', 'mid-back,lats', 'machine', 'weight_reps', ['Don\'t lift chest off the pad', 'Squeeze blades together']],
  ['Meadows Row (Dumbbell)', 'db meadows', 'pull', 'lats,upper back', 'dumbbell', 'weight_reps', ['Elbow out wide', 'Pull to the hip']],
  ['Seal Row (Barbell)', 'bb seal row', 'pull', 'mid-back', 'barbell,bench', 'weight_reps', ['Pull bar to the bench', 'Zero momentum']],
  ['Lat Pulldown (Underhand)', 'reverse grip pulldown', 'pull', 'lats,biceps', 'cable', 'weight_reps', ['Supinated grip', 'Pull to the lower chest']],
  ['Pull-Up (Weighted)', 'weighted pullup', 'pull', 'lats,biceps', 'pull-up bar', 'weight_reps', ['Start from a dead hang', 'Pull chin over bar']],
  ['Chin-Up (Weighted)', 'weighted chinup', 'pull', 'lats,biceps', 'pull-up bar', 'weight_reps', ['Control the negative', 'Full stretch at the bottom']],
  ['Rope Pullover', 'cable pullover', 'pull', 'lats', 'cable', 'weight_reps', ['Keep elbows slightly bent', 'Drive hands to hips']],
  ['Gorilla Row', 'gorilla row', 'pull', 'mid-back,lats', 'kettlebell', 'weight_reps', ['Hinge over two bells', 'Row one while pushing into the other']],

  // MORE PUSH / ARM / SHOULDERS (25)
  ['Floor Press (Dumbbell)', 'db floor press', 'push', 'chest,triceps', 'dumbbell', 'weight_reps', ['Pause when triceps hit floor', 'Explode up']],
  ['Svend Press', 'svend', 'push', 'chest', 'dumbbell', 'weight_reps', ['Pinch plates together', 'Press straight out from chest']],
  ['Decline Push-Up', 'decline pushup', 'push', 'upper chest', 'bodyweight', 'reps', ['Feet elevated', 'Maintain a straight body']],
  ['Deficit Push-Up', 'deficit pushup', 'push', 'chest', 'bodyweight', 'reps', ['Hands on plates or handles', 'Get a deep stretch']],
  ['Weighted Dip', 'dips weighted', 'push', 'chest,triceps', 'dip bars', 'weight_reps', ['Lean forward slightly', 'Control the descent']],
  ['Z-Press', 'z press', 'push', 'shoulders,core', 'barbell', 'weight_reps', ['Sit on the floor, legs straight', 'Don\'t lean back']],
  ['Z-Press (Dumbbell)', 'db z press', 'push', 'shoulders,core', 'dumbbell', 'weight_reps', ['Keep chest tall', 'Strict press']],
  ['Bradford Press', 'bradford', 'push', 'shoulders', 'barbell', 'weight_reps', ['Press just over the head to the back', 'Constant tension']],
  ['Cable Lateral Raise (Behind Back)', 'behind back lateral', 'push', 'side delts', 'cable', 'weight_reps', ['Lean slightly away', 'Lead with the elbow']],
  ['Y-Raise', 'y raise', 'push', 'side delts,traps', 'dumbbell,bench', 'weight_reps', ['Chest supported', 'Raise arms in a Y shape']],
  ['Plate Front Raise', 'plate raise', 'push', 'front delts', 'barbell', 'weight_reps', ['Twist the plate slightly at the top', 'Control the lowering']],
  ['Concentration Curl (Cable)', 'cable concentration', 'pull', 'biceps', 'cable', 'weight_reps', ['Strict form', 'Squeeze the bicep hard']],
  ['Spider Curl (Barbell)', 'bb spider curl', 'pull', 'biceps', 'barbell,bench', 'weight_reps', ['Chest on incline bench', 'Full range of motion']],
  ['Drag Curl', 'drag curl', 'pull', 'biceps', 'barbell', 'weight_reps', ['Drag bar up the body', 'Elbows go back']],
  ['French Press', 'seated french press', 'push', 'triceps', 'barbell,bench', 'weight_reps', ['Keep elbows tucked', 'Deep stretch behind head']],

  // MORE CORE / CARRY / MOBILITY / COND (25)
  ['Farmer\'s Carry (Trap Bar)', 'trap bar carry', 'carry', 'grip,core', 'trap bar', 'distance', ['Stand tall', 'Quick choppy steps']],
  ['Suitcase Carry (Kettlebell)', 'kb suitcase carry', 'carry', 'obliques,grip', 'kettlebell', 'distance', ['Stay perfectly vertical', 'Don\'t let the bell touch your leg']],
  ['Overhead Carry (Double)', 'double oh carry', 'carry', 'core,shoulders', 'kettlebell,dumbbell', 'distance', ['Biceps by ears', 'Ribs down']],
  ['Sandbag Load', 'sandbag to shoulder', 'carry', 'full body', 'sandbag', 'reps', ['Triple extension', 'Roll the bag over the shoulder']],
  ['Atlas Stone Load', 'stone load', 'carry', 'full body', 'atlas stone', 'reps', ['Lap the stone first', 'Extend hips hard']],
  ['Plank (Weighted)', 'weighted plank', 'core', 'core', 'bodyweight', 'time', ['Plate on the mid back', 'Squeeze glutes']],
  ['Ab Wheel (Standing)', 'standing rollout', 'core', 'core', 'bodyweight', 'reps', ['Only go as far as you can control', 'Keep hollow body']],
  ['Hollow Rock', 'hollow rocks', 'core', 'core', 'bodyweight', 'reps', ['Maintain the hollow position', 'Rock smoothly']],
  ['Turkish Get-Up', 'tgu', 'core', 'full body,shoulders', 'kettlebell', 'reps', ['Eye on the bell', 'Move methodically']],
  ['Windmill', 'kb windmill', 'core', 'obliques,shoulders', 'kettlebell', 'reps', ['Look at the bell', 'Hinge at the hips']],
  ['Sled Push (Heavy)', 'heavy prowler', 'conditioning', 'legs', 'sled', 'distance', ['Low angle', 'Drive through the toes']],
  ['Medicine Ball Slam', 'ball slam', 'conditioning', 'power,core', 'medicine ball', 'reps', ['Reach high', 'Slam it through the floor']],
  ['Kettlebell Clean', 'kb clean', 'conditioning', 'power', 'kettlebell', 'reps', ['Keep it close to the body', 'Zip the jacket']],
  ['Kettlebell Jerk', 'kb jerk', 'conditioning', 'power,shoulders', 'kettlebell', 'reps', ['Dip and drive', 'Catch under the bells']],
  ['Echo Bike Sprints', 'assault bike sprints', 'conditioning', 'cardio', 'machine', 'time', ['All out effort', 'Use arms and legs equally']],
  ['Prowler Sprint', 'sled sprint', 'conditioning', 'cardio', 'sled', 'distance', ['High handles', 'Sprint as fast as possible']],
  ['Scapular Pull-Up', 'scap pullup', 'mobility', 'back,shoulders', 'pull-up bar', 'reps', ['Keep arms straight', 'Depress the shoulder blades']],
  ['Jefferson Curl', 'j-curl', 'mobility', 'spine,hamstrings', 'barbell', 'reps', ['Segment the spine slowly', 'Keep knees locked']],
  ['Brettzel Stretch', 'brettzel', 'mobility', 'full body', 'bodyweight', 'time', ['Breathe deep', 'Try to get both shoulders to the floor']],
  ['Thread the Needle', 'thoracic stretch', 'mobility', 'upper back', 'bodyweight', 'reps', ['Reach far under', 'Open up to the ceiling']],
]
