import type { ExerciseCategory, TrackingType } from '../types'

export type SeedRow = [name: string, aliases: string, cat: ExerciseCategory, muscles: string, equip: string, track: TrackingType, cues: string[]]

export const p1: SeedRow[] = [
  // SQUAT (50)
  ['Zercher Squat', 'zercher', 'squat', 'quads,core,upper back', 'barbell', 'weight_reps', ['Hold bar in elbow crooks', 'Stay incredibly upright']],
  ['Heel-Elevated Goblet Squat', 'cyclist squat', 'squat', 'quads', 'dumbbell,kettlebell', 'weight_reps', ['Drive knees far forward', 'Keep torso totally vertical']],
  ['Paused Back Squat', 'pause squat', 'squat', 'quads,glutes', 'barbell,rack', 'weight_reps', ['Hold tension at the bottom', 'No bouncing out of the hole']],
  ['Pin Squat', 'anderson squat', 'squat', 'quads,glutes', 'barbell,rack', 'weight_reps', ['Start from a dead stop', 'Drive up hard']],
  ['Hack Squat', 'machine hack', 'squat', 'quads,glutes', 'machine', 'weight_reps', ['Keep lower back flat against pad', 'Control the descent']],
  ['Pendulum Squat', 'pendulum', 'squat', 'quads,glutes', 'machine', 'weight_reps', ['Ride the arc', 'Don\'t let knees cave in']],
  ['Belt Squat', 'pit shark', 'squat', 'quads,glutes', 'machine', 'weight_reps', ['Stay tall', 'Drive through the whole foot']],
  ['Smith Machine Squat', 'smith squat', 'squat', 'quads,glutes', 'machine', 'weight_reps', ['Feet slightly forward', 'Push back into the bar']],
  ['Sissy Squat', 'sissy', 'squat', 'quads', 'bodyweight', 'reps', ['Hips and torso in a straight line', 'Knees forward, heels up']],
  ['Spanish Squat', 'spanish', 'squat', 'quads', 'band,bodyweight', 'reps', ['Sit back against the band', 'Keep shins vertical']],
  ['Pistol Squat', 'one leg squat', 'squat', 'quads,glutes,core', 'bodyweight', 'reps', ['Control the eccentric', 'Keep the non-working leg straight']],
  ['Skater Squat', 'shrimp squat', 'squat', 'quads,glutes', 'bodyweight', 'reps', ['Reach forward as you descend', 'Tap the back knee gently']],
  ['B-Stance Squat', 'kickstand squat', 'squat', 'quads,glutes', 'barbell', 'weight_reps', ['80% weight on front leg', 'Back toe just for balance']],
  ['Safety Bar Squat', 'ssb squat', 'squat', 'quads,upper back', 'safety bar,rack', 'weight_reps', ['Fight the bar pulling you forward', 'Chest up']],
  ['Cambered Bar Squat', 'cambered', 'squat', 'quads,posterior chain', 'cambered bar,rack', 'weight_reps', ['Control the swing', 'Stay tight in the hole']],
  ['Frankenstein Squat', 'zombie squat', 'squat', 'quads,core', 'barbell,rack', 'weight_reps', ['Arms straight out', 'Don\'t let the bar roll']],
  ['Kang Squat', 'kang', 'squat', 'hamstrings,quads,glutes', 'barbell', 'weight_reps', ['Hinge first, then squat', 'Reverse the motion smoothly']],
  ['Split Squat', 'stationary lunge', 'squat', 'quads,glutes', 'dumbbell', 'weight_reps', ['Drop straight down', 'Don\'t lean forward too much']],
  ['Landmine Squat', 'landmine', 'squat', 'quads,core', 'barbell,landmine', 'weight_reps', ['Lean slightly into the bar', 'Drive up and in']],
  ['Landmine Hack Squat', 'landmine hack', 'squat', 'quads', 'barbell,landmine', 'weight_reps', ['Back to the plates', 'Feet out in front']],
  ['Jefferson Squat', 'jefferson lift', 'squat', 'quads,glutes', 'barbell', 'weight_reps', ['Straddle the bar', 'Keep torso neutral']],
  ['Wall Sit', 'wall squat', 'squat', 'quads', 'bodyweight', 'time', ['Thighs parallel to floor', 'Back flat against the wall']],
  ['V-Squat', 'v squat machine', 'squat', 'quads,glutes', 'machine', 'weight_reps', ['Heels planted firmly', 'Hips back into the pad']],
  ['Front Box Squat', 'box fs', 'squat', 'quads,core', 'barbell,box', 'weight_reps', ['Stay tight on the box', 'Elbows up']],
  ['Dumbbell Squat', 'db squat', 'squat', 'quads,glutes', 'dumbbell', 'weight_reps', ['Keep dumbbells at sides', 'Chest up']],
  ['Kettlebell Front Squat', 'kb fs,double kb squat', 'squat', 'quads,core', 'kettlebell', 'weight_reps', ['Keep bells racked tight', 'Elbows tucked']],
  ['Sandbag Squat', 'bear hug squat', 'squat', 'quads,core', 'sandbag', 'weight_reps', ['Hug the bag tight', 'Stay tall']],
  ['Overhead Squat', 'ohs', 'squat', 'quads,core,shoulders', 'barbell', 'weight_reps', ['Push up into the bar', 'Keep armpits forward']],
  ['Jump Squat', 'squat jump', 'squat', 'quads,calves', 'bodyweight', 'reps', ['Land softly', 'Explode up']],
  ['Frog Squat', 'frogger', 'squat', 'quads', 'bodyweight', 'reps', ['Keep hips lower than shoulders', 'Constant tension']],
  
  // HINGE (50)
  ['Stiff-Legged Deadlift', 'sldl', 'hinge', 'hamstrings,lower back', 'barbell', 'weight_reps', ['Keep knees mostly straight', 'Feel the stretch in the hamstrings']],
  ['Sumo Deadlift', 'sumo dl', 'hinge', 'glutes,quads,hamstrings', 'barbell', 'weight_reps', ['Wide stance, toes out', 'Spread the floor', 'Keep hips close to the bar']],
  ['Deficit Deadlift', 'deficit dl', 'hinge', 'hamstrings,glutes,back', 'barbell', 'weight_reps', ['Stand on a plate or small block', 'Longer pull, stay tight']],
  ['Block Pull', 'rack pull', 'hinge', 'back,glutes', 'barbell', 'weight_reps', ['Start from blocks or pins', 'Drive hips through']],
  ['Snatch Grip Deadlift', 'snatch dl', 'hinge', 'hamstrings,upper back', 'barbell', 'weight_reps', ['Wide grip', 'Keep lats incredibly tight']],
  ['B-Stance RDL', 'kickstand rdl', 'hinge', 'hamstrings,glutes', 'dumbbell,barbell', 'weight_reps', ['80% weight on front leg', 'Hinge on the working leg']],
  ['Single-Leg RDL', 'sl rdl', 'hinge', 'hamstrings,glutes,core', 'dumbbell', 'weight_reps', ['Hips square to the floor', 'Back leg kicks straight back']],
  ['Cable Pull-Through', 'pull through', 'hinge', 'glutes,hamstrings', 'cable', 'weight_reps', ['Soft knees, hinge back', 'Squeeze glutes to stand up']],
  ['Glute-Ham Raise', 'ghr', 'hinge', 'hamstrings,glutes', 'machine', 'reps', ['Keep a straight line from knees to shoulders', 'Pull with the hamstrings']],
  ['Nordic Hamstring Curl', 'nordics,nordic curl', 'hinge', 'hamstrings', 'bodyweight', 'reps', ['Control the fall', 'Catch yourself smoothly']],
  ['Back Extension', 'hyperextension,45 degree back extension', 'hinge', 'lower back,glutes,hamstrings', 'machine', 'weight_reps', ['Hinge at the hips, not the spine', 'Squeeze glutes at the top']],
  ['Reverse Hyper', 'reverse hyperextension', 'hinge', 'glutes,lower back', 'machine', 'weight_reps', ['Control the swing', 'Squeeze at the top']],
  ['Kettlebell Swing (American)', 'american swing', 'hinge', 'glutes,shoulders', 'kettlebell', 'reps', ['Swing all the way overhead', 'Ribs down']],
  ['Single-Arm Kettlebell Swing', '1a kb swing', 'hinge', 'glutes,core', 'kettlebell', 'reps', ['Resist the rotation', 'Snap the hips']],
  ['Dumbbell Deadlift', 'db deadlift', 'hinge', 'glutes,hamstrings', 'dumbbell', 'weight_reps', ['Keep dumbbells close to your legs', 'Hinge and drop']],
  ['Trap Bar RDL', 'hex bar rdl', 'hinge', 'hamstrings,glutes', 'trap bar', 'weight_reps', ['Hips back', 'Squeeze at the top']],
  ['Dimel Deadlift', 'dimel dl', 'hinge', 'hamstrings,glutes', 'barbell', 'weight_reps', ['Short range of motion', 'Explosive hip extension']],
  ['Banded RDL', 'band rdl', 'hinge', 'hamstrings,glutes', 'band', 'reps', ['Constant tension', 'Snap the hips']],
  ['Zercher Good Morning', 'zercher gm', 'hinge', 'hamstrings,core', 'barbell', 'weight_reps', ['Hold bar in elbow crooks', 'Hinge deep']],
  ['Seated Good Morning', 'seated gm', 'hinge', 'lower back,hips', 'barbell,bench', 'weight_reps', ['Wide stance', 'Hinge forward with a flat back']],
  ['Single-Leg Hip Thrust', 'sl thrust', 'hinge', 'glutes', 'bodyweight,dumbbell', 'weight_reps', ['Keep hips level', 'Drive through the heel']],
  ['B-Stance Hip Thrust', 'kickstand thrust', 'hinge', 'glutes', 'barbell', 'weight_reps', ['Focus on the working side', 'Squeeze hard']],
  ['Kas Glute Bridge', 'kas bridge', 'hinge', 'glutes', 'barbell,bench', 'weight_reps', ['Shorter ROM than a thrust', 'Constant glute tension']],
  ['Frog Pump', 'frog pump', 'hinge', 'glutes', 'bodyweight', 'reps', ['Feet together, knees out', 'Rapid reps']],
  ['Cable RDL', 'cable hinge', 'hinge', 'glutes,hamstrings', 'cable', 'weight_reps', ['Step back to get tension', 'Hinge back']],

  // PUSH (50)
  ['Incline Barbell Press', 'incline bench', 'push', 'upper chest,shoulders', 'barbell,bench', 'weight_reps', ['Bar touches upper chest', 'Drive back and up']],
  ['Decline Barbell Press', 'decline bench', 'push', 'lower chest,triceps', 'barbell,bench', 'weight_reps', ['Tuck elbows slightly', 'Press over lower chest']],
  ['Flat Dumbbell Press', 'db bench,db press', 'push', 'chest,triceps', 'dumbbell,bench', 'weight_reps', ['Get a deep stretch', 'Press up and in']],
  ['Decline Dumbbell Press', 'decline db', 'push', 'lower chest', 'dumbbell,bench', 'weight_reps', ['Keep shoulders pinned back', 'Control the stretch']],
  ['Machine Chest Press', 'chest press machine', 'push', 'chest,triceps', 'machine', 'weight_reps', ['Keep chest proud', 'Don\'t let shoulders roll forward']],
  ['Pec Deck', 'machine fly,butterfly', 'push', 'chest', 'machine', 'weight_reps', ['Slight bend in elbows', 'Squeeze the chest at the top']],
  ['Dumbbell Fly', 'db fly', 'push', 'chest', 'dumbbell,bench', 'weight_reps', ['Open up wide', 'Hug a barrel on the way up']],
  ['Incline Dumbbell Fly', 'incline db fly', 'push', 'upper chest', 'dumbbell,bench', 'weight_reps', ['Stretch the upper pecs', 'Squeeze at the top']],
  ['Push Press', 'pp', 'push', 'shoulders,triceps,legs', 'barbell', 'weight_reps', ['Dip and drive', 'Use leg drive to move the bar']],
  ['Seated Barbell Press', 'seated ohp', 'push', 'shoulders,triceps', 'barbell,bench', 'weight_reps', ['Keep back tight against the pad', 'Press straight up']],
  ['Arnold Press', 'arnolds', 'push', 'shoulders', 'dumbbell,bench', 'weight_reps', ['Start palms facing you', 'Rotate as you press']],
  ['Machine Shoulder Press', 'shoulder press machine', 'push', 'shoulders,triceps', 'machine', 'weight_reps', ['Control the eccentric', 'Don\'t arch lower back excessively']],
  ['Front Raise', 'front raise', 'push', 'front delts', 'dumbbell', 'weight_reps', ['Slight elbow bend', 'Raise to shoulder height']],
  ['Cable Lateral Raise', 'cable side raise', 'push', 'side delts', 'cable', 'weight_reps', ['Pull across the body', 'Constant tension']],
  ['Upright Row', 'upright row', 'push', 'side delts,traps', 'barbell,cable', 'weight_reps', ['Pull elbows high and outside', 'Keep bar close to body']],
  ['Skullcrusher', 'lying tricep extension,french press', 'push', 'triceps', 'barbell,bench', 'weight_reps', ['Elbows point straight up', 'Lower to the forehead or behind the head']],
  ['Tricep Pushdown', 'cable pushdown,rope pushdown', 'push', 'triceps', 'cable', 'weight_reps', ['Keep elbows pinned to your sides', 'Fully extend at the bottom']],
  ['Overhead Tricep Extension', 'overhead tricep ext', 'push', 'triceps', 'cable,dumbbell', 'weight_reps', ['Keep elbows relatively still', 'Get a deep stretch at the bottom']],
  ['Dumbbell Kickback', 'tricep kickback', 'push', 'triceps', 'dumbbell', 'weight_reps', ['Keep elbow high', 'Extend arm fully']],
  ['JM Press', 'jm press', 'push', 'triceps,chest', 'barbell,bench', 'weight_reps', ['Lower bar toward neck', 'Elbows stay tucked, rock them back']],
  ['Tate Press', 'tate press', 'push', 'triceps', 'dumbbell,bench', 'weight_reps', ['Elbows flare out', 'Dumbbells touch the chest']],
  ['Spoto Press', 'spoto', 'push', 'chest,triceps', 'barbell,bench', 'weight_reps', ['Pause the bar an inch off your chest', 'Stay completely tight']],
  ['Floor Press', 'floor press', 'push', 'chest,triceps', 'barbell', 'weight_reps', ['Legs straight or bent', 'Pause when triceps hit the floor']],
  ['Guillotine Press', 'neck press', 'push', 'chest', 'barbell,bench', 'weight_reps', ['Wide grip', 'Lower to the collarbone (carefully!)']],
  ['Landmine Press', 'landmine shoulder press', 'push', 'shoulders,upper chest', 'barbell,landmine', 'weight_reps', ['Lean into it', 'Press up and out']],

  // PULL (50)
  ['Pendlay Row', 'pendlay', 'pull', 'lats,mid-back', 'barbell', 'weight_reps', ['Start each rep from a dead stop on the floor', 'Explosive pull to the lower chest']],
  ['Meadows Row', 'meadows', 'pull', 'lats,upper back', 'barbell,landmine', 'weight_reps', ['Staggered stance', 'Pull elbow high and wide']],
  ['T-Bar Row', 't bar row', 'pull', 'lats,mid-back', 'machine,barbell', 'weight_reps', ['Keep chest supported or back flat', 'Pull to the belly']],
  ['Chest-Supported Row', 'chest supported row,seal row', 'pull', 'mid-back,lats', 'dumbbell,bench', 'weight_reps', ['Squeeze shoulder blades together', 'Don\'t use momentum']],
  ['Inverted Row', 'bodyweight row,australian pullup', 'pull', 'mid-back,lats', 'bodyweight,barbell', 'reps', ['Keep body in a straight line', 'Pull chest to the bar']],
  ['Renegade Row', 'renegade', 'pull', 'mid-back,core', 'dumbbell', 'weight_reps', ['Maintain a solid plank', 'Minimize hip rotation']],
  ['Kroc Row', 'kroc', 'pull', 'lats,upper back', 'dumbbell,bench', 'weight_reps', ['Heavy weight, high reps', 'Some body english is okay']],
  ['Straight-Arm Pulldown', 'straight arm pulldown', 'pull', 'lats', 'cable', 'weight_reps', ['Slight bend in elbows', 'Pull down in an arc']],
  ['Neutral Grip Pulldown', 'v-bar pulldown', 'pull', 'lats', 'cable', 'weight_reps', ['Pull to the chest', 'Keep elbows tucked in']],
  ['Single-Arm Pulldown', '1a pulldown', 'pull', 'lats', 'cable', 'weight_reps', ['Get a deep stretch at the top', 'Pull elbow to the hip']],
  ['Neutral Grip Pull-Up', 'hammer pullup', 'pull', 'lats,biceps', 'pull-up bar', 'weight_reps', ['Palms facing each other', 'Pull chest to the bar']],
  ['Muscle-Up', 'muscle up', 'pull', 'lats,triceps,core', 'pull-up bar', 'reps', ['Explosive pull', 'Fast transition over the bar']],
  ['Rack Chins', 'rack chin up', 'pull', 'lats,biceps', 'pull-up bar,box', 'weight_reps', ['Feet elevated on a box', 'Pull vertically']],
  ['Dumbbell Pullover', 'pullover', 'pull', 'lats,chest', 'dumbbell,bench', 'weight_reps', ['Keep hips low', 'Feel the stretch in the lats']],
  ['Cable Pullover', 'cable pullover', 'pull', 'lats', 'cable', 'weight_reps', ['Use a rope or straight bar', 'Keep tension constant']],
  ['Rear Delt Fly', 'reverse fly,rear delt raise', 'pull', 'rear delts', 'dumbbell', 'weight_reps', ['Slight bend in elbows', 'Squeeze the rear delts']],
  ['Reverse Pec Deck', 'machine rear delt', 'pull', 'rear delts', 'machine', 'weight_reps', ['Keep arms slightly bent', 'Don\'t pinch the shoulder blades too much']],
  ['Cable Rear Delt Fly', 'cable reverse fly', 'pull', 'rear delts', 'cable', 'weight_reps', ['Cross the cables', 'Pull outward and backward']],
  ['Preacher Curl', 'preacher', 'pull', 'biceps', 'barbell,machine', 'weight_reps', ['Keep armpits snug against the pad', 'Full stretch at the bottom']],
  ['Incline Dumbbell Curl', 'incline curl', 'pull', 'biceps', 'dumbbell,bench', 'weight_reps', ['Let arms hang straight down', 'Keep elbows back']],
  ['Concentration Curl', 'concentration curl', 'pull', 'biceps', 'dumbbell', 'weight_reps', ['Elbow braced against the inner thigh', 'Strict movement']],
  ['Spider Curl', 'spider curl', 'pull', 'biceps', 'dumbbell,bench', 'weight_reps', ['Lie face down on an incline bench', 'Let arms hang straight down']],
  ['Cable Curl', 'cable bicep curl', 'pull', 'biceps', 'cable', 'weight_reps', ['Keep elbows at your sides', 'Squeeze at the top']],
  ['Reverse Curl', 'reverse bicep curl', 'pull', 'brachialis,forearms', 'barbell,cable', 'weight_reps', ['Palms facing down', 'Keep elbows tucked']],
  ['Zottman Curl', 'zottman', 'pull', 'biceps,forearms', 'dumbbell', 'weight_reps', ['Curl up palms up', 'Rotate and lower palms down']],
  ['Wrist Curl', 'wrist curl', 'pull', 'forearms', 'barbell,dumbbell', 'weight_reps', ['Rest forearms on a bench', 'Curl the wrists up']],
  ['Reverse Wrist Curl', 'reverse wrist curl', 'pull', 'forearms', 'barbell,dumbbell', 'weight_reps', ['Palms facing down', 'Extend the wrists up']],
]
